### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [cworld1/notie#1]
Add material themed icon

**Comment by cworld1** [comment]
Sorry but... what's your mean? I've already followed the material design 3 (You) and even used the latest material icons. Maybe you need more descriptions of your mean.

**Comment by cworld1** [comment]
Thanks for your suggestions. I'll try it in the next few days.

**Comment by cworld1** [comment]
Released new version [2.1.0](https://github.com/cworld1/notie/releases/tag/2.1.0). Please update to enjoy :)
