### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by ThatOneCalculator** [cworld1/notie#3]
A monochrome icon would be great for Android  13+ home screens
![Screenshot_20240116-105550.png](https://github.com/cworld1/notie/assets/44733677/07f98338-f086-4c01-8721-a2f907d7f4af)

**Comment by cworld1** [comment]
#2 has making progress on it.

Please making sure you are using the latest version of the app, or giving me more system info about why it cannot work as expected.

**Comment by ThatOneCalculator** [comment]
I'm on 2.0.0, as 2.1.0 is not on IzzyOnDroid yet :(

**Comment by cworld1** [comment]
?! I don't know my repo has been added for that long time!🤪🤪 Thanks for your feedback. I'll try to solve it and add it to README document.
